/** Declaration file generated by dts-gen */

declare module 'v-mask' {
  export function VueMaskFilter(value: any, stringMask: any): any;

  export function VueMaskPlugin(Vue: any): void;

  export namespace VueMaskDirective {
    function bind(el: any, _ref: any): void;

    function componentUpdated(el: any, _ref2: any): void;

    function unbind(el: any): void;
  }
}
